import type { Metadata } from "next";
import { Geist, Geist_Mono , Courgette} from "next/font/google";
import "../globals.css";
import Header from "../_components/ui/Header/Header";
import MainProvider from "@/providers/mainProvider";
import Footer from "../_components/ui/Footer/Footer";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const corgeteFont = Courgette({
  weight:"400" ,
  subsets:['latin']
}) 

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${corgeteFont.className} antialiased`}
      >
        <Header fontFamily={corgeteFont} />
        <MainProvider>
          <main>
            {children}
          </main>
        </MainProvider>
        <Footer/>
      </body>
    </html>
  );
}
